version: "3.8"

services:
  nextjs:
    image: ghcr.io/inventive-business-solutions/thermax-frontend-docker:latest
    networks:
      - traefik-public
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.prod-redirect.redirectscheme.scheme=https
        # Change router name prefix from erpnext to the name of stack in case of multi bench setup
        - traefik.http.routers.nextjs-http.rule=Host(`thermaxenaibot.co.in`)
        - traefik.http.routers.nextjs-http.entrypoints=http
        # Remove following lines in case of local setup
        - traefik.http.routers.nextjs-http.middlewares=prod-redirect
        - traefik.http.routers.nextjs-https.rule=Host(`thermaxenaibot.co.in`)
        - traefik.http.routers.nextjs-https.entrypoints=https
        - traefik.http.routers.nextjs-https.tls=true
        - traefik.http.routers.nextjs-https.tls.certresolver=le
        - traefik.http.services.nextjs.loadbalancer.server.port=3000
    environment:
      - NODE_ENV=production

networks:
  traefik-public:
    external: true
